### ISSUE TITLE
Pricepolling

### ISSUE THREAD

**Issue by fxnh** [oanda/v20-java-samples#5]
On your PricePolling sample - have you tested this. how can it be that first currency has underscore
"EUR_USD" and the next ones / GBP/USD -?????? 

List<String> instruments = new ArrayList<>(
                Arrays.asList("EUR_USD", "USD/JPY", "GBP/USD", "USD/CHF"));

**Comment by fxnh** [comment]
Now Array is corrected but while I can read my account balance pice polling still does not work 
 PricingGetResponse resp = ctx.pricing.get(request); throws 400 error
(this is on fxtrade; with new published v20 jar file)

**Comment by HerbSears-OANDA** [comment]
What instruments are you requesting? A request for an invalid instrument would return a 400 error.

**Comment by fxnh** [comment]
I use the instruments Oanda has published in their sample program (PricePolling – see blow)  – all major currencies. Even if I just try EUR_USD or EUR_CHF  - and I actually have positions in this currencies it brings back 400

 

https://github.com/oanda/v20-java-samples/blob/master/src/main/java/com/oanda/v20/v20sample/PricePolling.java

 

 

 

Von: Herb Sears <notifications@github.com>
Antworten an: oanda/v20-java-samples <reply@reply.github.com>
Datum: Mittwoch, 8. November 2017 um 21:46
An: oanda/v20-java-samples <v20-java-samples@noreply.github.com>
Cc: Stefan Hauser <stefan.hauser@gmail.com>, Author <author@noreply.github.com>
Betreff: Re: [oanda/v20-java-samples] Pricepolling (#5)

 

What instruments are you requesting? A request for an invalid instrument would return a 400 error.

**Comment by HerbSears-OANDA** [comment]
A new version of the  v20 jar (3.0.21) is now available.  This version will include a more detailed message with the 400 error.  This should help determine what problem you are encountering - please re-run your sample with this new version.

**Comment by fxnh** [comment]
Just tried your PricPolling Exampl wih new jar 3.0.21. This is error I get

 

Exception in thread "main" java.lang.RuntimeException: 400 : null : null

                at com.oanda.v20.PricePolling.main(PricePolling.java:44)

Caused by: 400 : null : null

                at com.oanda.v20.Context.execute(Context.java:191)

                at com.oanda.v20.pricing.PricingContext.get(PricingContext.java:72)

                at com.oanda.v20.PricePolling.main(PricePolling.java:35)


A new version of the v20 jar (3.0.21) is now available. This version will include a more detailed message with the 400 error. This should help determine what problem you are encountering - please re-run your sample with this new version.

**Comment by fxnh** [comment]
I just tried. Please see below error message. As said I use the published pric polling sample and jar 3.021

 

Neli

 

===

 

 

 

Exception in thread "main" java.lang.RuntimeException: 400 : null : null

                at com.oanda.v20.PricePolling.main(PricePolling.java:44)

Caused by: 400 : null : null

                at com.oanda.v20.Context.execute(Context.java:191)

                at com.oanda.v20.pricing.PricingContext.get(PricingContext.java:72)

                at com.oanda.v20.PricePolling.main(PricePolling.java:35)

 

Von: Herb Sears <notifications@github.com>
Antworten an: oanda/v20-java-samples <reply@reply.github.com>
Datum: Mittwoch, 8. November 2017 um 23:07
An: oanda/v20-java-samples <v20-java-samples@noreply.github.com>
Cc: Stefan Hauser <stefan.hauser@gmail.com>, Author <author@noreply.github.com>
Betreff: Re: [oanda/v20-java-samples] Pricepolling (#5)

 

A new version of the v20 jar (3.0.21) is now available. This version will include a more detailed message with the 400 error. This should help determine what problem you are encountering - please re-run your sample with this new version.

**Comment by HerbSears-OANDA** [comment]
Hmm, that's strange -- there should be an actual error message instead of 'null'.  Can you please try the same request using curl:

`
curl -H "Content-Type: application/json" -H "Authorization: Bearer <AUTHENTICATION TOKEN>" "https://api-fxtrade.oanda.com/v3/accounts/<ACCOUNT>/pricing?instruments=EUR_USD%2CUSD_JPY%2CGBP_USD%2CUSD_CHF"
`

Replace `<AUTHENTICATION TOKEN>` and `<ACCOUNT>` with your values.

**Comment by fxnh** [comment]
Hi

 I downloaded curl tool – not exactly sure how this works and set token and account Id and got a message with prices back !! 
(using comand line tool with Admin rights). 

 
Still Java program fails
 

Hope this helps

**Comment by fxnh** [comment]
This is the error message I get in Java – running the Jar file also with Admin rights. I get the same error if I run directly in Eclipse

 

Neli

 

 

 

Exception in thread "main" java.lang.RuntimeException: 400 : null : null

        at com.oanda.v20.PricePolling.main(PricePolling.java:44)

Caused by: 400 : null : null

        at com.oanda.v20.Context.execute(Context.java:191)

        at com.oanda.v20.pricing.PricingContext.get(PricingContext.java:72)

        at com.oanda.v20.PricePolling.main(PricePolling.java:35)

 

D:\Java>

 

Von: Stefan Hauser <neli.andonova@googlemail.com>
Datum: Donnerstag, 9. November 2017 um 22:14
An: oanda/v20-java-samples <reply@reply.github.com>, oanda/v20-java-samples <v20-java-samples@noreply.github.com>
Cc: Author <author@noreply.github.com>
Betreff: Re: [oanda/v20-java-samples] Pricepolling (#5)

 

Hi

 

I downloaded curl tool – not exactly sure how this works and set token and account Id and got a message with prices back !! 
(using comand line tool with Admin rights). 

 

Still Java program fails

 

Hope this helps

 

Neli

 

 

 

Von: Herb Sears <notifications@github.com>
Antworten an: oanda/v20-java-samples <reply@reply.github.com>
Datum: Donnerstag, 9. November 2017 um 16:12
An: oanda/v20-java-samples <v20-java-samples@noreply.github.com>
Cc: Stefan Hauser <stefan.hauser@gmail.com>, Author <author@noreply.github.com>
Betreff: Re: [oanda/v20-java-samples] Pricepolling (#5)

 

Hmm, that's strange -- there should be an actual error message instead of 'null'. Can you please try the same request using curl:

curl -H "Content-Type: application/json" -H "Authorization: Bearer <AUTHENTICATION TOKEN>" "https://api-fxtrade.oanda.com/v3/accounts/<ACCOUNT>/pricing?instruments=EUR_USD%2CUSD_JPY%2CGBP_USD%2CUSD_CHF"

Replace <AUTHENTICATION TOKEN> and <ACCOUNT> with your values.

**Comment by fxnh** [comment]
Solved, reinstalled java and library
